### ISSUE TITLE
Cannot read property 'atlas' of undefined

### ISSUE THREAD

**Issue by emilberg** [rickyruiz/vue-azure-maps#1]
Thanks for this project, It looks really promising. But when I try to integrate the plugin in a project that uses TypeScript I get a strange error. 

I am following the instructions for implementing the plugin from the documentation 
(https://rickyruiz.github.io/vue-azure-maps/). 

But when I try to load a view which has the AzureMap component in it I get an error saying:  
Error in mounted hook: "TypeError: Cannot read property 'atlas' of undefined"

It seems like it's something that has with TypeScript to do. Because if I set up a new default test project with the Vue CLI that doesn't use TypeScript it works as expected. But if I set up the same test project and tell it to use TypeScript I get the error. 

It seems strange though because the error does not appear to me to be a typical error you would get if it was TypeScript that was the problem. So maybe there is something obvious that I am missing?

**Comment by rickyruiz** [comment]
I will look into this. Can you tell me the OS, Browser and Version you are using?

**Comment by emilberg** [comment]
1. Mac OS Mojave (10.14.4), Google Chrome (74.0.3729.131)
2. TypeScript 3.4.5
3. Vue (CLI) 3.7.0
4. vue-azure-maps 0.0.11

**Comment by rickyruiz** [comment]
I am not able to reproduce the issue. Could you create a repo with this problem for me to clone?

This is most likely a setup issue. The `main.ts` file should look something like this:

```
import Vue from "vue";
import VueAzureMaps from "vue-azure-maps";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "./registerServiceWorker";
import "vue-azure-maps/dist/vue-azure-maps.css";

Vue.config.productionTip = false;

// Key taken from Azure Maps examples
Vue.use(VueAzureMaps, {
  key: "tTk1JVEaeNvDkxxnxHm9cYaCvqlOq1u-fXTvyXn2XkA"
});

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");

```
Further explanation:

In the mounted life cycle hook of the `AzureMap` component, the `VueAzureMaps` instance is used, which, in your case, is causing the error `"TypeError: Cannot read property 'atlas' of undefined"`.

```
// Instantiate map to the HTMLElement with the auto-generated map id.
const map = new this.$_azureMaps.atlas.Map(this.mapId, options)
```

`$_azureMaps` is added atuomatically to Vue typings for you:

```
/**
 * Augment the typings of Vue.js
 */

import Vue from 'vue'
import { VueAzureMaps } from './vue-azure-maps'

declare module 'vue/types/vue' {
  interface Vue {
    $_azureMaps: VueAzureMaps
  }
}
```

**Comment by emilberg** [comment]
Hi,
Yes, you are right. It does work. I hadn't configured it in the right way. Was stressed and since I got that error in the other TS project I was thinking it was for the same reason and that the module wasn't working. Have to go back to the original project and examine that code more closely to see if I can find the reason for it not working there. Anyway thanks for looking into it and sorry for taking up your time.

**Comment by rickyruiz** [comment]
This library is a work in progress and is still missing features and better documentation, do not worry, I'm happy to help!

**Comment by ajsazevedo** [comment]
Hello,

I'm still getting this issue. However, my application uses a main.js instead of a main.ts.

this is my main:
`import Vue from 'vue';
import VueAzureMaps from "vue-azure-maps";
import axios from 'axios';
import inject from './VueInstanceInject';
import './stylus/main.styl';
import "vue-azure-maps/dist/vue-azure-maps.css";

import './Config';
import './plugins';
import './filters';

import App from './App';

Vue.config.productionTip = false;

// Key taken from Azure Maps examples
Vue.use(VueAzureMaps, {
  key: "myPassword"
});

axios.defaults.baseURL = process.env.VUE_APP_API_ENDPOINT;

// Caso precise injetar algo na instancia root do Vue
// utilize o arquivo @/vue-instance-inject
new Vue({
  el: '#app',
  ...inject,
  template: '<v-app><App/></v-app>',
  components: {// Declaração de componentes
    App },
});

// eslint-disable-next-line
import './interceptors';`

This is the error I get:
![image](https://user-images.githubusercontent.com/8632431/102531853-ced5a980-4081-11eb-82a6-235a5783c70e.png)


Are you still working on this project?
Any sugestions?


Thanks in advance

**Comment by rickyruiz** [comment]
Are you using the latest version? The CSS is not extracted anymore, yet you are referencing it there, might be using an older version. I do not know what your injected object is doing on the main Vue instance, might want to comment that out and check if it is not affecting the way Vue Azure Maps extends the main Vue instance prototype.

I am still maintaining this project, but I am redesigning and optimizing it. I will release a v1.0.0 with a few breaking changes. This new version is being written from the ground up and will have Vue 3 support.

**Comment by ajsazevedo** [comment]
@rickyruiz 

I'm using the last version (yarn add). The CSS was a try, from what I saw in different examples (I downloaded the project from https://codesandbox.io/s/5fs15?file=/src/components/RouteExample.vue:1548-1558).

Maybe it's the CLI version. When using the downloaded project (vue/cli 3.6.0) it works fine.

1. OS, Browser and Version
Windows 10, Microsoft Edge Version 87.0.664.60
2. Vue Cli version
@vue/cli 4.5.8
3. vue-azure-maps version
latest

Glad to know you are still working on it.

**Comment by rickyruiz** [comment]
@ajsazevedo I just published a new version (v.0.0.30), added vue as a peer dependency, but I think something else is causing your problem. 

Use your Azure Maps Key in the following codesandbox and it should work.
https://codesandbox.io/s/vue-azure-maps-v0030-g5fpo

I'm looking at the way you initialize your main Vue instance, maybe changing:

```js
new Vue({
  el: '#app',
  ...inject,
  template: '',
  components: {// Declaração de componentes
  App },
});
```

For
```js
new Vue({
  ...inject,
  render: (h) => h(App)
}).$mount("#app");
```

**Comment by ajsazevedo** [comment]
Morning @rickyruiz ,

Thank you for the response.

I made an application from scratch and added your new version, and it worked fine. Also worked using the codesandbox you provided.

In my application it did not. But I believe now it is a problem with the structure of my app.

Debugging, this section of your code sets the $_azureMaps with my subscription key and an loaded "atlas" object.
![image](https://user-images.githubusercontent.com/8632431/102779418-f1faa480-4372-11eb-9dc9-57624ff03ad7.png)

But when I get to the section of page that actually uses the _azureMaps, it is undefined, resulting on the error.

Is there a way to force the "install" part again, at any section, so _azureMaps will be defined?

**Comment by ajsazevedo** [comment]
I reinstalled the "vue-template-compiler" package and it worked. Thank you.
