### ISSUE TITLE
Support typescript?

### ISSUE THREAD

**Issue by vaibhavkumar049** [rickyruiz/vue-azure-maps#2]
Is this support typescript? If it is can you provide some sample app that you created with it

**Comment by vaibhavkumar049** [comment]
Yes it does actually,but I don't know how

**Comment by rickyruiz** [comment]
Yes, it does support TypeScript!

This library is not stable yet and I have not found the time to improve the documentation, but you can take a look at the [installation ](https://rickyruiz.github.io/vue-azure-maps/guide/installation.html) to get started.

Once you complete the installation, go to this [example](https://github.com/rickyruiz/vue-azure-maps/blob/master/src/components/vue-azure-maps/AzureMapExample.vue).

The `atlas` typings can be imported like so:

```
import { atlas } from 'vue-azure-maps'
```

And the components:

```
import {
  AzureMap,
  AzureMapDataSource,
  AzureMapHtmlMarker,
  AzureMapUserPosition,
  AzureMapPoint,
  AzureMapCircle,
  AzureMapLineString,
  AzureMapPolygon,
  AzureMapControl,
  AzureMapZoomControl,
  AzureMapPitchControl,
  AzureMapStyleControl,
  AzureMapCompassControl,
  AzureMapSymbolLayer,
  AzureMapPolygonLayer,
  AzureMapLineLayer,
  AzureMapHeatMapLayer,
  AzureMapImageLayer,
  AzureMapTileLayer,
} from 'vue-azure-maps'
```

If you have any other question I'm more than happy to help 😃.

**Comment by vaibhavkumar049** [comment]
Hey man thanks , I'll check it out and update you, If you need any help me documentation and in project let me know
