### ISSUE TITLE
Using AzureMapPopup

### ISSUE THREAD

**Issue by ajsazevedo** [rickyruiz/vue-azure-maps#23]
Hello @rickyruiz ,

I'm trying to use the component AzureMapPopup, but the map keep being displayed as an inline resource.
![image](https://user-images.githubusercontent.com/8632431/102799051-b8389680-4390-11eb-966f-ab9c437e1e64.png)

The message displayed on the console suggest using an injection for this, but i couldn't find an example

![image](https://user-images.githubusercontent.com/8632431/102798923-87f0f800-4390-11eb-8585-bbf5e0282e2c.png)

This is how I'm using the components:
![image](https://user-images.githubusercontent.com/8632431/102799760-b1f6ea00-4391-11eb-9bf2-57584fa737c6.png)

**Comment by rickyruiz** [comment]
@ajsazevedo The AzureMapPopup refers to this https://docs.microsoft.com/en-us/azure/azure-maps/map-add-popup

It is a popup inside the map, not a popup to display the map itself. If you want to do that, you would just need to create a modal component and use the AzureMap component there.

The AzureMap component can be styled using css or width & height props.

ie.

```
// Template
<AzureMap class="azure-map" />

// CSS
.azure-map {
  width: 100%;
  height: 100%;
}
```

In the general example of the project, you can see how the popup is used [here](https://github.com/rickyruiz/vue-azure-maps/blob/master/src/components/vue-azure-maps/AzureMapExample.vue#L71).

**Comment by ajsazevedo** [comment]
Managed to make the modal with Vue.js Modal.

The general example of the project was very helpful for other things.
