### ISSUE TITLE
Duplicate `azure-maps-control` dependencies

### ISSUE THREAD

**Issue by maschill92** [rickyruiz/vue-azure-maps#24]
Our `package.json` includes both `azure-maps-control` and `vue-azure-maps`.

When inspecting our decency graph via "[webpack bundle analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer)" I noticed that `vue-azure-maps` was quite sizable (larger than `azure-maps-control` even). 

After digging into the files generated in the build for this project, it seems that `azure-maps-control` in it's entirety is included in the bundle.

![img](https://user-images.githubusercontent.com/4692066/107535772-ad2b0700-6b86-11eb-8e16-a20e037fef40.jpg)

My suspicion is that this is caused by `import * as atlasJs from 'azure-maps-control/dist/atlas.min.js'` in [`install.ts`](https://github.com/rickyruiz/vue-azure-maps/blob/master/src/plugin/install.ts#L1).

Why was this method of importing used vs `import * as atlas from 'azure-maps-control'`?

Additionally, the application imports `azure-maps-control`'s CSS. Which results in duplicated CSS.

Any thoughts on this?

**Comment by rickyruiz** [comment]
Vue 2 version of Vue Azure Maps imports the whole 'azure-maps-control' library, including the CSS. This is something that I already changed in the Vue 3 version (I have not made the Vue 3 version public yet, but I will as soon as I feel it's stable enough).

I do plan to add `azure-maps-control` as a peer dependency on the Vue 2 version and change the way global map options are handled. I've been too focused and busy at work, I've been postponing this breaking change for a while now, but I will try to publish this improvement on Saturday.

**Comment by maschill92** [comment]
Ok, great! The change you are talking about on Saturday is the Vue 2 version, correct?

**Comment by rickyruiz** [comment]
@maschill92 Correct!
