### ISSUE TITLE
master is not working

### ISSUE THREAD

**Issue by vaibhavkumar049** [rickyruiz/vue-azure-maps#3]
I tried to clone this repo and did `npm i` and changed key but it is not working 
error in console 
 Error: Failed to retrieve the style definitions: TypeError: Failed to fetch
    at eval (webpack-internal:///./node_modules/azure-maps-control/dist/atlas.min.js:3844)
    at async Promise.all (:8080/index 1)

webpack-internal:///./node_modules/azure-maps-control/dist/atlas.min.js:3766

**Comment by rickyruiz** [comment]
Try using [yarn](https://yarnpkg.com/en/).

After you clone the repository, run `yarn` and it will install the dependencies.

**Comment by vaibhavkumar049** [comment]
![error](https://user-images.githubusercontent.com/36812649/58980481-140eef00-87ee-11e9-8f22-c671939ba415.png)

I did all of things you said , still I am getting this error

**Comment by vaibhavkumar049** [comment]
Sorry @rickyruiz , I find out that Azure map is not supported in India and that explains why I can't make a request to atlas 
![Screenshot from 2019-06-06 12-14-55](https://user-images.githubusercontent.com/36812649/59012875-3ccacf00-8856-11e9-8707-58455854a697.png)

**Comment by rickyruiz** [comment]
I'm sorry to hear that, I thought all regions were supported 😞.

Here's a [related question](https://stackoverflow.com/questions/53065862/azure-maps-api-workaround-for-unsupported-regions) that was answered by Ricky Brundritt, a Senior Program Manager for Azure Maps. Maybe you can ask if they are planning on supporting India any time soon.
