### ISSUE TITLE
Create Route from <AzureMapUserPosition /> to <AzureMapPoint />

### ISSUE THREAD

**Issue by jmorgan74** [rickyruiz/vue-azure-maps#4]
Hi @rickyruiz,

This is superb work, really good, please keep it up. 👍 

I'm trying to create a Route from the co-ords in <AzureMapUserPosition /> to another long/lat <AzureMapPoint /> so I need to get the co-ords out of these components to pass to the Route REST API.  Is there a nice, clean way to get the co-ords from the components, maybe through the $_azureMap injection?

Many thanks,

Jon.

**Comment by rickyruiz** [comment]
The `<AzureMapUserPosition />` component emits multiple events you can listen to:

```
enum AzureMapUserPositionEvent {
  Success = 'success',
  Error = 'error',
  PermissionDenied = 'permission-denied',
  PositionUnavailable = 'permission-unavailable',
  Timeout = 'timeout',
  UnknownError = 'unknown-error',
  Ready = 'ready',
}
```


The [`navigator.geolocation.getCurrentPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) method is used by this component. The method returns a [`Position`](https://developer.mozilla.org/en-US/docs/Web/API/Position) object when the permission is granted.

```
interface Position {
    readonly coords: Coordinates;
    readonly timestamp: number;
}
```

```

interface Coordinates {
    readonly accuracy: number;
    readonly altitude: number | null;
    readonly altitudeAccuracy: number | null;
    readonly heading: number | null;
    readonly latitude: number;
    readonly longitude: number;
    readonly speed: number | null;
}

```
The position is emmited in the `success` event of the `<AzureMapUserPosition />` component:

`this.$emit(AzureMapUserPositionEvent.Success, position)`


```
<AzureMapUserPosition
  // ...props
  @success="setUserPosition"
/>
```

```
methods: {
  setUserPosition({ coords: { longitude, latitude } }: Position): void {
    // this.userLongitude= longitude
    // this.userLatitude = latitude
  },
},
```

You can use those user coordinates and create a Route that points to the `<AzureMapPoint />` coordinates, using the [route directions map service](https://docs.microsoft.com/en-us/rest/api/maps/route/getroutedirections).

Here's a [working example](https://codesandbox.io/s/vue-azure-map-route-example-5fs15) to get you started.

**Comment by jmorgan74** [comment]
Hi Ricky,

That's fantastic! Thank you so much for the explanation and example.

Regards,

Jon.
