### ISSUE TITLE
Azure Map Clustering

### ISSUE THREAD

**Issue by Marimax01** [rickyruiz/vue-azure-maps#5]
How to allow clustering of the data source ?
I don't see anything about this in your DataSource component.

example [(AzureMapCodeSamples):](https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Bubble%20Layer/Point%20Clusters%20in%20Bubble%20Layer.html)
```
// Create a data source and add it to the map.
datasource = new atlas.source.DataSource (null, {
    // Tell the data source to cluster point data.
    cluster: true,
    // The radius in pixels to cluster points together.
    clusterRadius: 45,
    // The maximium zoom level in which clustering occurs.
    // If you zoom in on this, all points are rendered as symbols.
    clusterMaxZoom: 15
});
```

**Comment by rickyruiz** [comment]
The current version does not support the bubble layer yet. I'll try to add this feature tonight. This is a work in progress and many features are missing, I'm sorry for the inconvenience.

**Comment by rickyruiz** [comment]
A new version has been released with this feature. Please reopen this issue if you face any problems.

**Comment by Marimax01** [comment]
Thanks for your reactivity. It works.
