### ISSUE TITLE
[Supported Browser] Error on Firefox 68.0.1

### ISSUE THREAD

**Issue by Marimax01** [rickyruiz/vue-azure-maps#7]
Hi,
I would like to know on which browser you are testing your plugin?
Because at first I was only testing on chrome and I had no problem.
But recently I wanted to test on Firefox but I have errors with the promises.
I removed all my dependencies to see which one was making this mistake.
It seems to be yours.
A polyfills story, apparently. 
It is natively supported by Firefox since its version 58.
[https://caniuse.com/#search=promise](https://caniuse.com/#search=promise)

Can you give me the compatibility of the browsers with your plugin please 
 and make a correction if you find the same thing as me?

**Comment by rickyruiz** [comment]
@Marimax01 Firefox does not display any errors for me. I'm using vue-azure-maps v0.0.24 and Firefox version 68.0.1 (64-bit) Windows 10.

As far as I know you should not have problems with any browser. I've tested it with Chrome, Firefox, Edge and Safari.

Could you provide a reproduction link or the following information:
Firefox version: 
OS: 
Log messages given by the failure:

**Comment by Marimax01** [comment]
Hi, I'm sorry for the wait. 
I created a simple [project](https://github.com/Marimax01/promise-error) to show you my problem.

In this project I installed Axios and vue-azure-map in addition to the packages installed by vue cli.
I just have a component called homeView. In this one I use an [API](https://api.chucknorris.io/)
In my main.ts I have the line to initialize your package if you launch like this on Mozilla you have a mistake. Now how the initialization phase and you have no error in al console.

Thank you for the thanks you have given to help me.

**Comment by rickyruiz** [comment]
The problem is related to `core-js` package and `Promise.prototype.finally()` polyfill, not this library. See https://github.com/vuejs/vue-cli/issues/2012

In the following code block in your `Home` view, you use `finally`:

      http
        .get("https://api.chucknorris.io/jokes/random")
        .then(response => {
          this.joke = response.data.value;
        })
        .catch(error => {
          this.joke = error;
        })
        .finally(() => { // <-- This throws an error in FireFox.
          this.isLoaded = true;
        });

You could use `try {} catch {} finally {}` instead to fix the issue.

**Comment by Marimax01** [comment]
I saw the core-js problem but it's just by commenting in the main.ts file that it changes.

With this code in my main.ts:
`import Vue from 'vue';`
`import App from './App.vue';`
`import router from './router';`
`import store from './store';`

`import VueAzureMaps from 'vue-azure-maps';`
`import 'vue-azure-maps/dist/vue-azure-maps.css';`

`Vue.use(VueAzureMaps, {`
`  key: '<Your Azure Maps key>',`
`});`

`Vue.config.productionTip = false;`

`new Vue({`
`  router,`
`  store,`
`  render: (h) => h(App),`
`}).$mount('#app');`

I have an error
![image](https://user-images.githubusercontent.com/12886336/62921861-2a1acc00-bdaa-11e9-88fc-a96c89d7968e.png)

but when my main.ts is : 

`import Vue from 'vue';`
`import App from './App.vue';`
`import router from './router';`
`import store from './store';`

`import VueAzureMaps from 'vue-azure-maps';`
`import 'vue-azure-maps/dist/vue-azure-maps.css';`

`//Vue.use(VueAzureMaps, {`
`//  key: '<Your Azure Maps key>',`
`//});`

`Vue.config.productionTip = false;`

`new Vue({`
`  router,`
`  store,`
`  render: (h) => h(App),`
`}).$mount('#app');`

I have no error, the promise works,  just  by comments initialisation of vue-azure-map, i don't touch anything else of my project.

![image](https://user-images.githubusercontent.com/12886336/62921953-70702b00-bdaa-11e9-9827-e0bc2c02b171.png)

**Comment by Marimax01** [comment]
Did you find out what the problem is?

**Comment by rickyruiz** [comment]
@Marimax01 Sorry for the late response, I have not had the time to work on this library lately. I am looking into this. The problem seems to be that the `promise.prototype.finally` is being overwritten.

When you import the `vue-azure-maps` library, the following code gets included:

```
"use strict";
// https://github.com/tc39/proposal-promise-finally

var $export = __webpack_require__("63b6");
var core = __webpack_require__("584a");
var global = __webpack_require__("e53d");
var speciesConstructor = __webpack_require__("f201");
var promiseResolve = __webpack_require__("cd78");

$export($export.P + $export.R, 'Promise', { 'finally': function (onFinally) {
  var C = speciesConstructor(this, core.Promise || global.Promise);
  var isFunction = typeof onFinally == 'function';
  return this.then(
    isFunction ? function (x) {
      return promiseResolve(C, onFinally()).then(function () { return x; });
    } : onFinally,
    isFunction ? function (e) {
      return promiseResolve(C, onFinally()).then(function () { throw e; });
    } : onFinally
  );
} });
```

I did not have `useBuiltIns` set to `false`, which is recommended for libraries [here](https://cli.vuejs.org/guide/browser-compatibility.html#polyfills-when-building-as-library-or-web-components). This should fix the issue and the consuming app should now be responsible for including polyfills if needed.

**Comment by rickyruiz** [comment]
@Marimax01 Upgrade to version `0.0.27`.
